In [1]:
import torch 
import torch.nn as nn
 
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out    

In [2]:
#creating dataset
df=torch.rand(2,3)
df
#creating model 
model=Model(df.shape[1])
#calling model 
model(df)

tensor([[0.5207],
        [0.5314]], grad_fn=<SigmoidBackward0>)

In [3]:
model.linear.weight

Parameter containing:
tensor([[ 0.4196,  0.2683, -0.4871]], requires_grad=True)

task to create a neural network which consit of a input layer where it takes 5 inputs a hidde layer which contains 3 sections which has activation func relu and a output layer whose activation fucntion is sigmoid

In [4]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.layer1=nn.Linear(num_features,3)
        self.relu=nn.ReLU()
        self.layer2=nn.linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.layer1(features)
        out=self.relu(out)
        out=self.layer2(out)
        out=self.sigmoid(out)

        return out    

**using the sequential layer** to reduce down the work 


In [5]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())
    def forward(self,features):
        out = self.network(features)

        return out    

In [6]:
#creating dataset
df=torch.rand(10,5)
df
#creating model 
model=Model(df.shape[1])
#calling model 
model(df)


tensor([[0.5056],
        [0.5145],
        [0.4905],
        [0.5003],
        [0.5382],
        [0.5063],
        [0.4948],
        [0.5266],
        [0.5154],
        [0.4939]], grad_fn=<SigmoidBackward0>)

In [ ]:
#using hte built in loss func
loss_function=nn.BCELoss()
#loss= loss_fucntion(y_pred,y_traintenosr)

In [ ]:
#using the builtin optimizier
#defining the optimizier
optimizer= torch.optim.SGD(model.parameters(),lr=0.1)
#parameters_update
optimizer.step()