In [42]:
from sklearn.datasets import make_classification
import torch

In [43]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [44]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [45]:
from torch.utils.data import Dataset,DataLoader


In [46]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
            return self.features.shape[0]
    def __getitem__(self,index):
         return self.features[index],self.labels[index]
         


In [47]:
dataset=CustomDataset(X,y)


In [48]:
len(dataset)

10

In [49]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=False,num_workers=2)

In [50]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
