In [76]:
import torch
print(torch.__version__)

2.9.0+cu126


In [77]:
if torch.cuda.is_available():
    print("gpu available")
    print(torch.cuda.get_device_name(0))
else:
    print("gpu not available ")    

gpu available
Tesla T4


CREATING TENSOR IN PYTORCH 

In [78]:
#using empty 
a= torch.empty(2,3)#2d tensor
b=torch.rand(2,3)
c=torch.zeros(2,3,33)#3d tensor
d=torch.ones(2,3)
e= torch.eye(2,3)#used for identity matrix


In [79]:
#creating the seed manually so that the random fucn genrates the same value even by running it everytime
torch.manual_seed(100)
torch.rand(2,3)
#now if i run this cell everytime i got the same output

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [80]:
#custom tensor
torch.tensor([[2,3,4],[4,5,6]])

tensor([[2, 3, 4],
        [4, 5, 6]])

In [81]:
torch.arange(2,33,4)#always return an 1d tenosr
torch.linspace(2,33,10)

tensor([ 2.0000,  5.4444,  8.8889, 12.3333, 15.7778, 19.2222, 22.6667, 26.1111,
        29.5556, 33.0000])

TENSOR SHAPE 


In [82]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
x.shape

torch.Size([2, 3])

In [84]:
torch.empty_like(x)


tensor([[   785688192,    785663408,    683226264],
        [   536870912, 459561500672, 408021893221]])

In [85]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [86]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [87]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

TENSOR DATATYPE

In [88]:
print(x.dtype)

torch.int64


In [89]:
#assinging datatype
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


**Mathematical Operations** 

In [90]:
x= torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [91]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

**ELEMENT WISE OPERATION**

In [92]:
a= torch.rand(2,3)
b=torch.rand(2,3)

In [93]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])
tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])
tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])
tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])
tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])


In [94]:
c = torch.tensor([1, -2, 3, -4])
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [95]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [96]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
# round
torch.round(d)

tensor([2., 2., 4., 4.])

REduction operations 

In [97]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [98]:
print(torch.sum(e))
print(torch.sum(e,dim=0))#sum along column
print(torch.sum(e,dim=1))#sum along row 

tensor(28.)
tensor([16.,  5.,  7.])
tensor([ 7., 21.])


In [99]:
print(torch.mean(e))
print(torch.mean(e,dim=0))
print(torch.mean(e,dim=1))

tensor(4.6667)
tensor([8.0000, 2.5000, 3.5000])
tensor([2.3333, 7.0000])


In [100]:
# median
torch.median(e)

tensor(5.)

In [101]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [102]:
# product
torch.prod(e)

tensor(0.)

In [103]:
# standard deviation
torch.std(e)
# variance
torch.var(e)
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(1)

Matrix operations 

In [104]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[116, 126],
        [ 80,  98]])

In [106]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [110]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [111]:
#determinant
torch.det(h)

tensor(-135.0000)

In [112]:
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

In [113]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


tensor([[True, True, True],
        [True, True, True]])

In [115]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [116]:
print(torch.log(k))
print(torch.exp(k))
print(torch.sqrt(k))
print(torch.sigmoid(k))
print(torch.softmax(k,dim=0))
print(torch.relu(k))

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])
tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])
tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])
tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])
tensor([[0.7311, 0.5000, 0.1192],
        [0.2689, 0.5000, 0.8808]])
tensor([[5., 0., 6.],
        [4., 0., 8.]])
